### ISSUE TITLE
Cooperation of Wtczycki Tasmoticz with Energy Panel in Domoticz

### ISSUE THREAD

**Issue by Daro1003** [joba-1/Tasmoticz#51] opened 2024-10-06 14:23 UTC
Devices built on the basis of PZEM and Tasmota do not cooperate with the Energy panel in Domoticz. So I started a topic on the domoticz forum: https://www.domoticz.com/forum/viewtopic.php?t=42564

I received this tip from one of the users:
"Ask the plugin author to create a Domoticz Electricicity (instant and counter) device if the tasmota device sends Usage (Watt) and total Energy (kWh).
In python plugin framework this is device type 243, subtype 29"

I would like to ask you to edit the plugin so that data from the PZEM meter can be used in the Energy Panel in Domoticz.

**Comment by joba-1** [comment] 2024-10-06 17:19
I consider it, but I don’t have a pzem, so I have no idea what kind of messages tasmota sends for it and I cannot test.
I would at least need all mqtt messages tasmota sends from boot until the first tele message.
Also I need to know the required domoticz version.

**Comment by joba-1** [comment] 2024-10-06 17:21
closing. Duplicate of #46
Feel free to answer there

**Closed as completed by joba-1** 2024-10-06 17:21 UTC

**Comment by Daro1003** [comment] 2024-10-06 18:12
How can I help you in this case?
